### ISSUE TITLE
install -r requirements failed on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Zombymumf** [carltongibson/rest-framework-tutorial#10]
Running through the installation process got this error:

...
Installing collected packages: six, asn1crypto, pycparser, cffi, idna, cryptography, python-dateutil, PyJWT, certifi, urllib3, chardet, requests, adal, pycodestyle, autopep8, azure-nspkg, azure-mgmt-nspkg, azure-common, isodate, oauthlib, requests-oauthlib, msrest, msrestazure, azure-mgmt-containerservice, azure-mgmt-loganalytics, azure-mgmt-containerregistry, azure-mgmt-logic, azure-mgmt-redis, azure-mgmt-cdn, azure-mgmt-datalake-nspkg, azure-mgmt-datalake-analytics, azure-mgmt-rdbms, azure-mgmt-powerbiembedded, azure-mgmt-authorization, azure-mgmt-machinelearningcompute, azure-mgmt-managementgroups, azure-mgmt-consumption, azure-mgmt-billing, azure-mgmt-sql, azure-mgmt-eventhub, azure-mgmt-iotcentral, azure-mgmt-compute, azure-mgmt-search, azure-mgmt-iothub, azure-mgmt-keyvault, azure-mgmt-monitor, azure-mgmt-datalake-store, azure-mgmt-relay, azure-mgmt-commerce, azure-mgmt-maps, azure-mgmt-advisor, azure-mgmt-cosmosdb, azure-mgmt-eventgrid, azure-mgmt-managementpartner, azure-mgmt-recoveryservicesbackup, azure-mgmt-servicefabric, azure-mgmt-datafactory, azure-mgmt-resource, azure-mgmt-containerinstance, azure-mgmt-signalr, azure-mgmt-marketplaceordering, azure-mgmt-recoveryservices, azure-mgmt-subscription, azure-mgmt-msi, azure-mgmt-policyinsights, azure-mgmt-reservations, azure-mgmt-batchai, azure-mgmt-scheduler, azure-mgmt-storage, azure-mgmt-iothubprovisioningservices, azure-mgmt-hanaonazure, azure-mgmt-datamigration, azure-mgmt-devspaces, azure-mgmt-network, azure-mgmt-applicationinsights, azure-mgmt-batch, azure-mgmt-cognitiveservices, azure-mgmt-notificationhubs, azure-mgmt-trafficmanager, azure-mgmt-servicebus, azure-mgmt-devtestlabs, azure-mgmt-media, azure-mgmt-web, azure-mgmt-dns, azure-mgmt, azure-servicefabric, azure-loganalytics, azure-eventgrid, azure-keyvault, azure-storage-common, azure-storage-blob, azure-storage-queue, azure-cosmosdb-nspkg, azure-cosmosdb-table, azure-datalake-store, azure-graphrbac, azure-storage-file, azure-servicemanagement-legacy, azure-servicebus, azure-applicationinsights, azure-batch, azure, azure-functions, grpcio, setuptools, protobuf, grpcio-tools, azure-functions-worker, azure-functions-wsgi-adapter, Click, MarkupSafe, Jinja2, coreschema, uritemplate, itypes, coreapi, dj-database-url, pytz, Django, django-storages, djangorestframework, mccabe, pyflakes, flake8, gunicorn, Markdown, psycopg2, Pygments, python-dotenv, whitenoise
  Running setup.py install for autopep8 ... done
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
  Running setup.py install for MarkupSafe ... error
    Complete output from command /home/gary/envs/django/drf_tutorial/drf_env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r4nw26om/MarkupSafe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-o0x0fx9s-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/gary/envs/django/drf_tutorial/drf_env/include/site/python3.6/MarkupSafe:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-r4nw26om/MarkupSafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    
    ----------------------------------------
Command "/home/gary/envs/django/drf_tutorial/drf_env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r4nw26om/MarkupSafe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-o0x0fx9s-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/gary/envs/django/drf_tutorial/drf_env/include/site/python3.6/MarkupSafe" failed with error code 1 in /tmp/pip-build-r4nw26om/MarkupSafe/

**Comment by carltongibson** [comment]
I guess you need to update setuptools? Can't really advise. 16.04 was a long time ago...
