### ISSUE TITLE
Doing it from the powershell

### ISSUE THREAD

**Issue by Tajjun** [carltongibson/rest-framework-tutorial#5]
Hi,
What would be the command "$ export $(grep -v '^#' .azure-env | xargs)" with powershell ?

**Comment by carltongibson** [comment]
No idea. Sorry.

**Comment by carltongibson** [comment]
I don't think this is actionable as is. (Since powershell isn't something I use.) I'd happily accept a PR adding the instructions though.

**Comment by Tajjun** [comment]
Thanks Carlton, I opened a PR
