### ISSUE TITLE
Error while running pip install - r requirements.txt on windows

### ISSUE THREAD

**Issue by bsocket** [carltongibson/rest-framework-tutorial#6]
creating pip-egg-info\psycopg2.egg-info
    writing pip-egg-info\psycopg2.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\psycopg2.egg-info\dependency_links.txt
    writing top-level names to pip-egg-info\psycopg2.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\psycopg2.egg-info\SOURCES.txt'
    Error: pg_config executable not found.

    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ajay\AppData\Local\Temp\pip-install-zqmkjzos\psycopg2\

**Comment by keizof** [comment]
Installing PostgreSQL which contains pg_config fixed the error for me.

For Mac,
> brew install postgresql

For Windows, try if this solution works: https://stackoverflow.com/questions/36846579/error-when-installing-psycopg2-on-windows-10
