### ISSUE TITLE
Unable to install requirements from requirements.txt.

### ISSUE THREAD

**Issue by ghost** [carltongibson/rest-framework-tutorial#9]
OS:MAC
It fails with the below error :
Collecting psycopg2==2.7.3.2 (from -r requirements.txt (line 115))
  Using cached https://files.pythonhosted.org/packages/dd/47/000b405d73ca22980684fd7bd3318690cc03cfa3b2ae1c5b7fff8050b28a/psycopg2-2.7.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: pg_config executable not found.
    
    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jm/r0pp4jj54x70ks5yg2_fm2v40000gn/T/pip-install-fddjl9ba/psycopg2/
You are using pip version 19.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by carltongibson** [comment]
You're missing Postgres' `pg_config`. Try https://postgresapp.com/

(Or, also, try `psycopg2-binary` instead...)
